# Generated by Django 2.1.3 on 2018-12-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181202_2124'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='카드의 등장 순서')),
                ('place', models.CharField(choices=[('DECK', '덱'), ('DUNGEON', '던전'), ('PLAYER', '플레이어')], max_length=16)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MonsterClass')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
