# Generated by Django 2.1.3 on 2018-12-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181202_2124'),
        ('session', '0002_monster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('place', models.CharField(choices=[('EQUIPPED', '장비'), ('REMOVE', '제거')], default='EQUIPPED', max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ItemClass')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemovedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='monster',
            name='place',
            field=models.CharField(choices=[('DECK', '덱'), ('DUNGEON', '던전'), ('REMOVE', '제거'), ('DEFEATED', '무찌름')], default='DECK', max_length=16),
        ),
        migrations.AddField(
            model_name='removedpackage',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Monster'),
        ),
        migrations.AddField(
            model_name='removedpackage',
            name='room_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.RoomPlayer'),
        ),
    ]
