# Generated by Django 2.1.3 on 2018-12-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20181202_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('state', models.CharField(choices=[('PLAY', '진행'), ('END', '종료')], default='PLAY', help_text='라운드의 진행 상태', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='room',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='room',
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='life',
            field=models.PositiveSmallIntegerField(default=2, help_text='플레이어의 기회'),
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='trophy',
            field=models.PositiveSmallIntegerField(default=0, help_text='플레이어가 던전을 점령한 횟수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('READY', '준비'), ('PLAY', '진행'), ('END', '종료')], default='READY', help_text='방의 진행 상태', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='removedpackage',
            name='round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Round'),
            preserve_default=False,
        ),
    ]
