# Generated by Django 2.1.3 on 2018-12-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20181202_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('state', models.CharField(choices=[('PLAY', '게임중'), ('PASS', '패스'), ('DUNGEON', '던전'), ('FAIL', '던전 실패'), ('SUCCESS', '던전 성공')], default='PLAY', max_length=16)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='removedpackage',
            name='room_player',
        ),
        migrations.RemoveField(
            model_name='removedpackage',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='life',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='trophy',
        ),
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='라운드 회차'),
        ),
        migrations.AddField(
            model_name='round',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='state',
            field=models.CharField(choices=[('JOIN', '참여중'), ('LEAVE', '떠남'), ('WIN', '게임 승리'), ('LOSE', '게임 패배')], help_text='플레이어의 방 참여 상태', max_length=16),
        ),
        migrations.AddField(
            model_name='roundplayer',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Round'),
        ),
        migrations.AddField(
            model_name='removedpackage',
            name='round_player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.RoundPlayer'),
            preserve_default=False,
        ),
    ]
