# Generated by Django 2.1.3 on 2018-12-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20181202_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
