# Generated by Django 2.1.3 on 2018-12-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20181205_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplayer',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='name',
        ),
        migrations.AddField(
            model_name='round',
            name='desc',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(default=None, help_text='이름', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
