# Generated by Django 2.1.3 on 2018-12-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20181205_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='round',
            name='name',
        ),
    ]
