# Generated by Django 2.1.3 on 2019-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190113_0757'),
        ('session', '0011_auto_20181205_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='defeat',
            field=models.ManyToManyField(blank=True, null=True, to='game.MonsterClass'),
        ),
    ]
