# Generated by Django 2.1.3 on 2019-01-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_item_defeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='defeat',
            field=models.ManyToManyField(blank=True, to='game.MonsterClass'),
        ),
    ]
