# Generated by Django 2.1.3 on 2018-12-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181202_0134'),
        ('dungeonofmandom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMixin',
        ),
    ]
