# Generated by Django 2.1.3 on 2018-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterclass',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, help_text='게임에 들어가는 카드 장 수'),
        ),
    ]
