# Generated by Django 2.1.3 on 2018-12-02 12:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('game', '0005_auto_20181202_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobClass',
            new_name='HeroClass',
        ),
        migrations.RenameModel(
            old_name='EquipmentClass',
            new_name='ItemClass',
        ),
    ]
