# Generated by Django 2.1.3 on 2018-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181202_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroclass',
            name='desc',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
        migrations.AlterField(
            model_name='itemclass',
            name='desc',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
        migrations.AlterField(
            model_name='monsterclass',
            name='desc',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
    ]
