# Generated by Django 2.1.3 on 2018-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181202_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclass',
            name='hero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.HeroClass'),
            preserve_default=False,
        ),
    ]
