# Generated by Django 2.1.3 on 2018-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_itemclass_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='defeat',
            field=models.ManyToManyField(blank=True, null=True, to='game.MonsterClass'),
        ),
    ]
