# Generated by Django 2.1.3 on 2019-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20181202_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='defeat',
            field=models.ManyToManyField(blank=True, null=True, to='game.MonsterClass'),
        ),
    ]
