# Generated by Django 2.1.3 on 2019-01-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190113_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='defeat',
            field=models.ManyToManyField(blank=True, to='game.MonsterClass'),
        ),
    ]
